<a href="https://colab.research.google.com/github/Miliyas/Generative_AI/blob/main/Attention_model_mib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re
import torch
import pickle
import numpy as np
import pandas as pd
from tqdm import tqdm
import torch.nn as nn
from nltk.tokenize import word_tokenize
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
lr = 0.0005
vec_len = 50
seq_len = 20
num_epochs = 50
label_col = "Product"
tokens_path = "Output/tokens.pkl"
labels_path = "Output/labels.pkl"
data_path = "/content/drive/MyDrive/complaints_new.csv"
model_path = "Output/attention.pth"
vocabulary_path = "Output/vocabulary.pkl"
embeddings_path = "Output/embeddings.pkl"
glove_vector_path = "/content/drive/MyDrive/glove.6B.50d.txt"
text_col_name = "Consumer complaint narrative"
label_encoder_path = "Output/label_encoder.pkl"
product_map = {'Vehicle loan or lease': 'vehicle_loan',
               'Credit reporting, credit repair services, or other personal consumer reports': 'credit_report',
               'Credit card or prepaid card': 'card',
               'Money transfer, virtual currency, or money service': 'money_transfer',
               'virtual currency': 'money_transfer',
               'Mortgage': 'mortgage',
               'Payday loan, title loan, or personal loan': 'loan',
               'Debt collection': 'debt_collection',
               'Checking or savings account': 'savings_account',
               'Credit card': 'card',
               'Bank account or service': 'savings_account',
               'Credit reporting': 'credit_report',
               'Prepaid card': 'card',
               'Payday loan': 'loan',
               'Other financial service': 'others',
               'Virtual currency': 'money_transfer',
               'Student loan': 'loan',
               'Consumer Loan': 'loan',
               'Money transfers': 'money_transfer'}

In [4]:
mkdir Output

In [5]:
def save_file(name, obj):
    """
    Function to save an object as pickle file
    """
    with open(name, 'wb') as f:
        pickle.dump(obj, f)


def load_file(name):
    """
    Function to load a pickle object
    """
    return pickle.load(open(name, "rb"))

# **Different word embedding techniques**

**word2vec**

In [ ]:
pip install gensim


In [ ]:
import gensim.downloader as api

# Download the pre-trained model
model = api.load("word2vec-google-news-300")

# Save the model to a file
model.save("word2vec-google-news-300.model")


[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
import gensim

# Load a pre-trained Word2Vec model
from gensim.models import KeyedVectors

# Load the model
model = KeyedVectors.load("word2vec-google-news-300.model", mmap='r')

# Get the vector for a word
word_vector = model['computer']

# Find similar words
similar_words = model.most_similar('computer')

# Print the results
print(f"Word: 'computer', Vector: {word_vector}")
print(f"Similar words: {similar_words}")

Word: 'computer', Vector: [ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01

In [ ]:
similar_words = model.most_similar('king')
print(similar_words)


[('kings', 0.7138045430183411), ('queen', 0.6510956883430481), ('monarch', 0.6413194537162781), ('crown_prince', 0.6204220056533813), ('prince', 0.6159993410110474), ('sultan', 0.5864824056625366), ('ruler', 0.5797567367553711), ('princes', 0.5646552443504333), ('Prince_Paras', 0.5432944297790527), ('throne', 0.5422105193138123)]


**GloVe**

## Process glove embeddings
---

In [6]:
with open(glove_vector_path, "rt") as f:
    emb = f.readlines()

In [7]:
vocabulary, embeddings = [], []

for item in emb:
    vocabulary.append(item.split()[0])
    embeddings.append(item.split()[1:])

In [8]:
#convert list into numpy array
embeddings = np.array(embeddings, dtype=np.float32)

In [9]:
vocabulary = ["<pad>", "<unk>"] + vocabulary

In [10]:
embeddings = np.vstack([np.ones(50, dtype=np.float32),
                        np.mean(embeddings, axis=0),
                        embeddings])

In [11]:
embeddings

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-0.12920076, -0.28866628, -0.01224866, ...,  0.10069408,
         0.00653003,  0.01685157],
       [ 0.418     ,  0.24968   , -0.41242   , ..., -0.18411   ,
        -0.11514   , -0.78581   ],
       ...,
       [-0.51181   ,  0.058706  ,  1.0913    , ..., -0.25003   ,
        -1.125     ,  1.5863    ],
       [-0.75898   , -0.47426   ,  0.4737    , ...,  0.78954   ,
        -0.014116  ,  0.6448    ],
       [ 0.072617  , -0.51393   ,  0.4728    , ..., -0.18907   ,
        -0.59021   ,  0.55559   ]], dtype=float32)

In [12]:
embeddings.shape

(400002, 50)

In [13]:
save_file(embeddings_path, embeddings)
save_file(vocabulary_path, vocabulary)

## Process text data
---

In [14]:
data = pd.read_csv(data_path)

In [15]:
data.head()

Product  \
0                              Vehicle loan or lease   
1  Credit reporting, credit repair services, or o...   
2  Credit reporting, credit repair services, or o...   
3  Credit reporting, credit repair services, or o...   
4  Credit reporting, credit repair services, or o...   

                        Consumer complaint narrative  
0  I contacted Ally on Friday XX/XX/XXXX after fa...  
1  Hello This complaint is against the three cred...  
2  I am a victim of Identity Theft & currently ha...  
3  Two accounts are still on my credit history af...  
4  Receiving daily telephone call ( s ) from XXXX...

In [16]:
data.dropna(subset=[text_col_name], inplace=True)

In [17]:
data.replace({label_col: product_map}, inplace=True)

### Encode labels

**LabelEncoder**

In [18]:
['apple', 'banana', 'orange', 'apple', 'banana']
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
encoded_fruits = le.fit_transform(['apple', 'banana', 'orange', 'apple', 'banana'])

print(encoded_fruits)

[0 1 2 0 1]


**OneHotEncoder:**


In [19]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)
encoded_fruits = ohe.fit_transform(np.array(['apple', 'banana', 'orange', 'apple', 'banana']).reshape(-1, 1))

print(encoded_fruits)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


**LabelEncoder**

In [20]:
label_encoder = LabelEncoder()
label_encoder.fit(data[label_col])
label_encoder.classes_

array(['card', 'credit_report', 'debt_collection', 'loan',
       'money_transfer', 'mortgage', 'others', 'savings_account',
       'vehicle_loan'], dtype=object)

In [21]:
labels = label_encoder.transform(data[label_col])

In [22]:
labels

array([8, 1, 1, ..., 5, 1, 1])

In [23]:
list(label_encoder.inverse_transform([8, 1, 1,5]))

['vehicle_loan', 'credit_report', 'credit_report', 'mortgage']

In [24]:
save_file(labels_path, labels)
save_file(label_encoder_path, label_encoder)

### Process the text column

In [25]:
type(data[text_col_name])

pandas.core.series.Series

In [26]:
input_text = list(data[text_col_name])

In [27]:
len(input_text)

809343

### Convert text to lower case

In [28]:
input_text = [i.lower() for i in tqdm(input_text)]

100%|██████████| 809343/809343 [00:01<00:00, 696058.20it/s]


### Remove punctuations except apostrophe

In [29]:
input_text = [re.sub(r"[^\w\d'\s]+", " ", i)
              for i in tqdm(input_text)]

100%|██████████| 809343/809343 [00:24<00:00, 32458.83it/s]


### Remove digits

In [30]:
input_text = [re.sub("\d+", "", i) for i in tqdm(input_text)]

100%|██████████| 809343/809343 [00:15<00:00, 52309.52it/s]


### Remove more than one consecutive instance of 'x'

In [31]:
input_text = [re.sub(r'[x]{2,}', "", i) for i in tqdm(input_text)]

100%|██████████| 809343/809343 [00:13<00:00, 61349.06it/s]


### Remove multiple spaces with single space

In [32]:
input_text = [re.sub(' +', ' ', i) for i in tqdm(input_text)]

100%|██████████| 809343/809343 [00:40<00:00, 20032.65it/s]


### Tokenize the text

In [33]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [34]:
tokens = [word_tokenize(t) for t in tqdm(input_text)]

100%|██████████| 809343/809343 [06:54<00:00, 1952.27it/s]


### Take the first 20 tokens in each complaint text

In [35]:
tokens[0][:20]

['i',
 'contacted',
 'ally',
 'on',
 'friday',
 'after',
 'falling',
 'behind',
 'on',
 'payments',
 'due',
 'to',
 'being',
 'out',
 'of',
 'work',
 'for',
 'a',
 'short',
 'period']

In [36]:
tokens = [i[:20] if len(i) > 19 else ['<pad>'] * (20 - len(i)) + i
          for i in tqdm(tokens)]

100%|██████████| 809343/809343 [00:10<00:00, 80186.81it/s]


### Convert tokens to integer indices from vocabulary

In [37]:
def token_index(tokens, vocabulary, missing='<unk>'):
    """
    :param tokens: List of word tokens
    :param vocabulary: All words in the embeddings
    :param missing: Token for words not present in the vocabulary
    :return: List of integers representing the word tokens
    """
    idx_token = []
    for text in tqdm(tokens):
        idx_text = []
        for token in text:
            if token in vocabulary:
                idx_text.append(vocabulary.index(token))
            else:
                idx_text.append(vocabulary.index(missing))
        idx_token.append(idx_text)
    return idx_token

In [38]:
print(vocabulary.index('credit'))

1166


In [39]:
len(vocabulary)

400002

In [40]:
tokens = token_index(tokens, vocabulary)

100%|██████████| 809343/809343 [1:38:29<00:00, 136.97it/s]


### Save the tokens

In [41]:
save_file(tokens_path, tokens)

## Create attention model
---

In [42]:
class AttentionModel(nn.Module):

    def __init__(self, vec_len, seq_len, n_classes):
        super(AttentionModel, self).__init__()
        self.vec_len = vec_len
        self.seq_len = seq_len
        self.attn_weights = torch.cat([torch.tensor([[0.]]),
                                       torch.randn(vec_len, 1) /
                                       torch.sqrt(torch.tensor(vec_len))])
        self.attn_weights.requires_grad = True
        self.attn_weights = nn.Parameter(self.attn_weights)
        self.activation = nn.Tanh()
        self.softmax = nn.Softmax(dim=1)
        self.linear = nn.Linear(vec_len + 1, n_classes)

    def forward(self, input_data):
        hidden = torch.matmul(input_data, self.attn_weights)
        hidden = self.activation(hidden)
        attn = self.softmax(hidden)
        attn = attn.repeat(1, 1, self.vec_len + 1).reshape(attn.shape[0],
                                                           self.seq_len,
                                                           self.vec_len + 1)
        attn_output = input_data * attn
        attn_output = torch.sum(attn_output, axis=1)
        output = self.linear(attn_output)
        return output

## Create PyTorch dataset
---

In [43]:
class TextDataset(torch.utils.data.Dataset):

    def __init__(self, tokens, embeddings, labels):
        """
        :param tokens: List of word tokens
        :param embeddings: Word embeddings (from glove)
        :param labels: List of labels
        """
        self.tokens = tokens
        self.embeddings = embeddings
        self.labels = labels

    def __len__(self):
        return len(self.tokens)

    def __getitem__(self, idx):
        emb = torch.tensor(self.embeddings[self.tokens[idx], :])
        input_ = torch.cat((torch.ones(emb.shape[0],1), emb), dim=1)
        return torch.tensor(self.labels[idx]), input_

### Function to train the model

In [44]:
def train(train_loader, valid_loader, model, criterion, optimizer,
          device, num_epochs, model_path):
    """
    Function to train the model
    :param train_loader: Data loader for train dataset
    :param valid_loader: Data loader for validation dataset
    :param model: Model object
    :param criterion: Loss function
    :param optimizer: Optimizer
    :param device: CUDA or CPU
    :param num_epochs: Number of epochs
    :param model_path: Path to save the model
    """
    best_loss = 1e8
    for i in range(num_epochs):
        print(f"Epoch {i+1} of {num_epochs}")
        valid_loss, train_loss = [], []
        model.train()
        # Train loop
        for batch_labels, batch_data in tqdm(train_loader):
            # Move data to GPU if available
            batch_labels = batch_labels.to(device)
            batch_data = batch_data.to(device)
            # Forward pass
            batch_output = model(batch_data)
            batch_output = torch.squeeze(batch_output)
            # Calculate loss
            loss = criterion(batch_output, batch_labels)
            train_loss.append(loss.item())
            optimizer.zero_grad()
            # Backward pass
            loss.backward()
            # Gradient update step
            optimizer.step()
        model.eval()
        # Validation loop
        for batch_labels, batch_data in tqdm(valid_loader):
            # Move data to GPU if available
            batch_labels = batch_labels.to(device)
            batch_data = batch_data.to(device)
            # Forward pass
            batch_output = model(batch_data)
            batch_output = torch.squeeze(batch_output)
            # Calculate loss
            loss = criterion(batch_output, batch_labels)
            valid_loss.append(loss.item())
        t_loss = np.mean(train_loss)
        v_loss = np.mean(valid_loss)
        print(f"Train Loss: {t_loss}, Validation Loss: {v_loss}")
        if v_loss < best_loss:
            best_loss = v_loss
            # Save model if validation loss improves
            torch.save(model.state_dict(), model_path)
        print(f"Best Validation Loss: {best_loss}")

### Function to test the model

In [45]:
def test(test_loader, model, criterion, device):
    """
    Function to test the model
    :param test_loader: Data loader for test dataset
    :param model: Model object
    :param criterion: Loss function
    :param device: CUDA or CPU
    """
    model.eval()
    test_loss = []
    test_accu = []
    for batch_labels, batch_data in tqdm(test_loader):
        # Move data to device
        batch_labels = batch_labels.to(device)
        batch_data = batch_data.to(device)
        # Forward pass
        batch_output = model(batch_data)
        batch_output = torch.squeeze(batch_output)
        # Calculate loss
        loss = criterion(batch_output, batch_labels)
        test_loss.append(loss.item())
        batch_preds = torch.argmax(batch_output, axis=1)
        # Move predictions to CPU
        if torch.cuda.is_available():
            batch_labels = batch_labels.cpu()
            batch_preds = batch_preds.cpu()
        # Compute accuracy
        test_accu.append(accuracy_score(batch_labels.detach().
                                        numpy(),
                                        batch_preds.detach().
                                        numpy()))
    test_loss = np.mean(test_loss)
    test_accu = np.mean(test_accu)
    print(f"Test Loss: {test_loss}, Test Accuracy: {test_accu}")

## Train attention model
---

### Load the files

In [46]:
tokens = load_file(tokens_path)
labels = load_file(labels_path)
embeddings = load_file(embeddings_path)
label_encoder = load_file(label_encoder_path)
num_classes = len(label_encoder.classes_)
vocabulary = load_file(vocabulary_path)

### Split data into train, validation and test sets

In [47]:
X_train, X_test, y_train, y_test = train_test_split(tokens, labels,
                                                    test_size=0.2)
X_train, X_valid, y_train, y_valid = train_test_split(X_train,
                                                      y_train,
                                                      test_size=0.25)

### Create PyTorch datasets

In [48]:
train_dataset = TextDataset(X_train, embeddings, y_train)
valid_dataset = TextDataset(X_valid, embeddings, y_valid)
test_dataset = TextDataset(X_test, embeddings, y_test)

### Create data loaders

In [49]:
train_loader = torch.utils.data.DataLoader(train_dataset,
                                           batch_size=16,
                                           shuffle=True,
                                           drop_last=True)
valid_loader = torch.utils.data.DataLoader(valid_dataset,
                                           batch_size=16)
test_loader = torch.utils.data.DataLoader(test_dataset,
                                          batch_size=16)

### Create model object

In [50]:
device = torch.device("cuda:0" if torch.cuda.is_available()
                      else "cpu")

In [52]:
device

device(type='cuda', index=0)

In [51]:
model = AttentionModel(vec_len, seq_len, num_classes)

### Move the model to GPU if available

In [53]:
if torch.cuda.is_available():
    model = model.cuda()

### Define loss function and optimizer

In [54]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=lr)

### Training loop

In [55]:
train(train_loader, valid_loader, model, criterion, optimizer,
      device, num_epochs, model_path)

Epoch 1 of 50


100%|██████████| 10117/10117 [00:12<00:00, 796.84it/s]


Train Loss: 1.080838189019501, Validation Loss: 1.0014305693235772
Best Validation Loss: 1.0014305693235772
Epoch 2 of 50


100%|██████████| 10117/10117 [00:12<00:00, 815.79it/s]


Train Loss: 0.9894175603067659, Validation Loss: 0.9844283009778491
Best Validation Loss: 0.9844283009778491
Epoch 3 of 50


100%|██████████| 10117/10117 [00:12<00:00, 809.42it/s]


Train Loss: 0.9781256016480078, Validation Loss: 0.9767103254076307
Best Validation Loss: 0.9767103254076307
Epoch 4 of 50


100%|██████████| 10117/10117 [00:12<00:00, 818.55it/s]


Train Loss: 0.9723424341017763, Validation Loss: 0.9727864006715199
Best Validation Loss: 0.9727864006715199
Epoch 5 of 50


100%|██████████| 10117/10117 [00:12<00:00, 810.20it/s]


Train Loss: 0.9693475377211068, Validation Loss: 0.9699805529310002
Best Validation Loss: 0.9699805529310002
Epoch 6 of 50


100%|██████████| 10117/10117 [00:12<00:00, 831.58it/s]


Train Loss: 0.9675655721115712, Validation Loss: 0.9691451537381687
Best Validation Loss: 0.9691451537381687
Epoch 7 of 50


100%|██████████| 10117/10117 [00:12<00:00, 811.59it/s]


Train Loss: 0.9662540860398008, Validation Loss: 0.9677499180091302
Best Validation Loss: 0.9677499180091302
Epoch 8 of 50


100%|██████████| 10117/10117 [00:12<00:00, 824.14it/s]


Train Loss: 0.9653825810458357, Validation Loss: 0.9670434173852356
Best Validation Loss: 0.9670434173852356
Epoch 9 of 50


100%|██████████| 10117/10117 [00:12<00:00, 824.65it/s]


Train Loss: 0.9645460983830975, Validation Loss: 0.9661481403748933
Best Validation Loss: 0.9661481403748933
Epoch 10 of 50


100%|██████████| 10117/10117 [00:12<00:00, 811.09it/s]


Train Loss: 0.9639604168978122, Validation Loss: 0.9661341512098347
Best Validation Loss: 0.9661341512098347
Epoch 11 of 50


100%|██████████| 10117/10117 [00:12<00:00, 817.58it/s]


Train Loss: 0.9634070699272871, Validation Loss: 0.9656189188922336
Best Validation Loss: 0.9656189188922336
Epoch 12 of 50


100%|██████████| 10117/10117 [00:12<00:00, 821.90it/s]


Train Loss: 0.9629071326006382, Validation Loss: 0.9651261630151493
Best Validation Loss: 0.9651261630151493
Epoch 13 of 50


100%|██████████| 10117/10117 [00:12<00:00, 815.02it/s]


Train Loss: 0.9625135467310714, Validation Loss: 0.9649470233305695
Best Validation Loss: 0.9649470233305695
Epoch 14 of 50


100%|██████████| 10117/10117 [00:12<00:00, 828.64it/s]


Train Loss: 0.9621099790724538, Validation Loss: 0.9640056976110105
Best Validation Loss: 0.9640056976110105
Epoch 15 of 50


100%|██████████| 10117/10117 [00:12<00:00, 801.32it/s]


Train Loss: 0.9617539064996129, Validation Loss: 0.9638703008838424
Best Validation Loss: 0.9638703008838424
Epoch 16 of 50


100%|██████████| 10117/10117 [00:12<00:00, 803.48it/s]


Train Loss: 0.9613679616077139, Validation Loss: 0.9635958167004164
Best Validation Loss: 0.9635958167004164
Epoch 17 of 50


100%|██████████| 10117/10117 [00:12<00:00, 800.86it/s]


Train Loss: 0.9610276933316344, Validation Loss: 0.9631686509745482
Best Validation Loss: 0.9631686509745482
Epoch 18 of 50


100%|██████████| 10117/10117 [00:12<00:00, 801.79it/s]


Train Loss: 0.9607352078947833, Validation Loss: 0.9632776611505484
Best Validation Loss: 0.9631686509745482
Epoch 19 of 50


100%|██████████| 10117/10117 [00:12<00:00, 795.88it/s]


Train Loss: 0.960392573207764, Validation Loss: 0.9641503529773937
Best Validation Loss: 0.9631686509745482
Epoch 20 of 50


100%|██████████| 10117/10117 [00:12<00:00, 815.10it/s]


Train Loss: 0.960158870098913, Validation Loss: 0.9633441571854339
Best Validation Loss: 0.9631686509745482
Epoch 21 of 50


100%|██████████| 10117/10117 [00:12<00:00, 821.80it/s]


Train Loss: 0.9598139090867962, Validation Loss: 0.9630439024430744
Best Validation Loss: 0.9630439024430744
Epoch 22 of 50


100%|██████████| 10117/10117 [00:12<00:00, 802.40it/s]


Train Loss: 0.9595305122624119, Validation Loss: 0.962083101575997
Best Validation Loss: 0.962083101575997
Epoch 23 of 50


100%|██████████| 10117/10117 [00:12<00:00, 803.56it/s]


Train Loss: 0.9593145588128728, Validation Loss: 0.9628136661332669
Best Validation Loss: 0.962083101575997
Epoch 24 of 50


100%|██████████| 10117/10117 [00:12<00:00, 796.72it/s]


Train Loss: 0.9590323805489885, Validation Loss: 0.9621153140069233
Best Validation Loss: 0.962083101575997
Epoch 25 of 50


100%|██████████| 10117/10117 [00:12<00:00, 800.98it/s]


Train Loss: 0.9587762660995935, Validation Loss: 0.9621085804156474
Best Validation Loss: 0.962083101575997
Epoch 26 of 50


100%|██████████| 10117/10117 [00:12<00:00, 805.19it/s]


Train Loss: 0.9586721077013939, Validation Loss: 0.9608358737492592
Best Validation Loss: 0.9608358737492592
Epoch 27 of 50


100%|██████████| 10117/10117 [00:12<00:00, 798.89it/s]


Train Loss: 0.9583620029614235, Validation Loss: 0.9603829137731285
Best Validation Loss: 0.9603829137731285
Epoch 28 of 50


100%|██████████| 10117/10117 [00:12<00:00, 801.46it/s]


Train Loss: 0.9581688287574338, Validation Loss: 0.9611327309090358
Best Validation Loss: 0.9603829137731285
Epoch 29 of 50


100%|██████████| 10117/10117 [00:12<00:00, 794.96it/s]


Train Loss: 0.9579549489490675, Validation Loss: 0.9603487026497606
Best Validation Loss: 0.9603487026497606
Epoch 30 of 50


100%|██████████| 10117/10117 [00:12<00:00, 796.47it/s]


Train Loss: 0.9578302535434334, Validation Loss: 0.960440704962641
Best Validation Loss: 0.9603487026497606
Epoch 31 of 50


100%|██████████| 10117/10117 [00:12<00:00, 796.01it/s]


Train Loss: 0.9575580133264501, Validation Loss: 0.9602460875625582
Best Validation Loss: 0.9602460875625582
Epoch 32 of 50


100%|██████████| 10117/10117 [00:13<00:00, 771.96it/s]


Train Loss: 0.9574576276938448, Validation Loss: 0.9600036683950521
Best Validation Loss: 0.9600036683950521
Epoch 33 of 50


100%|██████████| 10117/10117 [00:12<00:00, 791.30it/s]


Train Loss: 0.9572327607197463, Validation Loss: 0.9594737882963857
Best Validation Loss: 0.9594737882963857
Epoch 34 of 50


100%|██████████| 10117/10117 [00:12<00:00, 803.54it/s]


Train Loss: 0.9570185957385052, Validation Loss: 0.9592368901129401
Best Validation Loss: 0.9592368901129401
Epoch 35 of 50


100%|██████████| 10117/10117 [00:12<00:00, 809.42it/s]


Train Loss: 0.9568864408061768, Validation Loss: 0.9603292272739452
Best Validation Loss: 0.9592368901129401
Epoch 36 of 50


100%|██████████| 10117/10117 [00:12<00:00, 797.86it/s]


Train Loss: 0.9566973406395567, Validation Loss: 0.9588349363358346
Best Validation Loss: 0.9588349363358346
Epoch 37 of 50


100%|██████████| 10117/10117 [00:12<00:00, 788.83it/s]


Train Loss: 0.956573510796961, Validation Loss: 0.9594122423780546
Best Validation Loss: 0.9588349363358346
Epoch 38 of 50


100%|██████████| 10117/10117 [00:12<00:00, 805.54it/s]


Train Loss: 0.9563697834006055, Validation Loss: 0.9587832669033132
Best Validation Loss: 0.9587832669033132
Epoch 39 of 50


100%|██████████| 10117/10117 [00:12<00:00, 810.42it/s]


Train Loss: 0.9562170460535431, Validation Loss: 0.9584406167386583
Best Validation Loss: 0.9584406167386583
Epoch 40 of 50


100%|██████████| 10117/10117 [00:12<00:00, 808.18it/s]


Train Loss: 0.9560485528009335, Validation Loss: 0.958999562585461
Best Validation Loss: 0.9584406167386583
Epoch 41 of 50


100%|██████████| 10117/10117 [00:12<00:00, 802.54it/s]


Train Loss: 0.955833714231235, Validation Loss: 0.9592010797372128
Best Validation Loss: 0.9584406167386583
Epoch 42 of 50


100%|██████████| 10117/10117 [00:12<00:00, 802.68it/s]


Train Loss: 0.9556968948357973, Validation Loss: 0.958282997419479
Best Validation Loss: 0.958282997419479
Epoch 43 of 50


100%|██████████| 10117/10117 [00:12<00:00, 808.22it/s]


Train Loss: 0.9554516622929833, Validation Loss: 0.9578015154646098
Best Validation Loss: 0.9578015154646098
Epoch 44 of 50


100%|██████████| 10117/10117 [00:12<00:00, 796.52it/s]


Train Loss: 0.9552561445453218, Validation Loss: 0.9588277385241195
Best Validation Loss: 0.9578015154646098
Epoch 45 of 50


100%|██████████| 10117/10117 [00:12<00:00, 822.34it/s]


Train Loss: 0.9551183771888251, Validation Loss: 0.9587772366845515
Best Validation Loss: 0.9578015154646098
Epoch 46 of 50


100%|██████████| 10117/10117 [00:12<00:00, 810.60it/s]


Train Loss: 0.9549260489679443, Validation Loss: 0.9577859823863663
Best Validation Loss: 0.9577859823863663
Epoch 47 of 50


100%|██████████| 10117/10117 [00:12<00:00, 803.47it/s]


Train Loss: 0.9547588930844868, Validation Loss: 0.9569038221389983
Best Validation Loss: 0.9569038221389983
Epoch 48 of 50


100%|██████████| 10117/10117 [00:12<00:00, 807.69it/s]


Train Loss: 0.9545122117039792, Validation Loss: 0.9568092063889739
Best Validation Loss: 0.9568092063889739
Epoch 49 of 50


100%|██████████| 10117/10117 [00:12<00:00, 797.04it/s]


Train Loss: 0.9543354374209582, Validation Loss: 0.956332837391173
Best Validation Loss: 0.956332837391173
Epoch 50 of 50


100%|██████████| 10117/10117 [00:12<00:00, 810.49it/s]

Train Loss: 0.9538907272399355, Validation Loss: 0.9557613654871685
Best Validation Loss: 0.9557613654871685


### Test the model

In [56]:
test(test_loader, model, criterion, device)

100%|██████████| 10117/10117 [00:18<00:00, 536.92it/s]

Test Loss: 0.9557410880527065, Test Accuracy: 0.6720979919556573


## Predict on new text
---

In [57]:
input_text = '''I am a victim of Identity Theft & currently have an Experian account that
I can view my Experian Credit Report and getting notified when there is activity on
my Experian Credit Report. For the past 3 days I've spent a total of approximately 9
hours on the phone with Experian. Every time I call I get transferred repeatedly and
then my last transfer and automated message states to press 1 and leave a message and
someone would call me. Every time I press 1 I get an automatic message stating than you
before I even leave a message and get disconnected. I call Experian again, explain what
is happening and the process begins again with the same end result. I was trying to have
this issue attended and resolved informally but I give up after 9 hours. There are hard
hit inquiries on my Experian Credit Report that are fraud, I didn't authorize, or recall
and I respectfully request that Experian remove the hard hit inquiries immediately just
like they've done in the past when I was able to speak to a live Experian representative
in the United States. The following are the hard hit inquiries : BK OF XXXX XX/XX/XXXX
XXXX XXXX XXXX  XX/XX/XXXX XXXX  XXXX XXXX  XX/XX/XXXX XXXX  XX/XX/XXXX XXXX  XXXX
XX/XX/XXXX'''

### Process input text

In [58]:
input_text = input_text.lower()
input_text = re.sub(r"[^\w\d'\s]+", " ", input_text)
input_text = re.sub("\d+", "", input_text)
input_text = re.sub(r'[x]{2,}', "", input_text)
input_text = re.sub(' +', ' ', input_text)
tokens = word_tokenize(input_text)

In [59]:
tokens = ['<pad>']*(20-len(tokens))+tokens

In [60]:
idx_token = []
for token in tokens:
    if token in vocabulary:
        idx_token.append(vocabulary.index(token))
    else:
        idx_token.append(vocabulary.index('<unk>'))

In [61]:
token_emb = embeddings[idx_token,:]
token_emb = token_emb[:seq_len, :]
inp = torch.from_numpy(token_emb)

In [62]:
inp = torch.cat((torch.ones(inp.shape[0],1), inp), dim=1)

In [63]:
device = torch.device("cuda:0" if torch.cuda.is_available()
                      else "cpu")

In [64]:
inp = inp.to(device)
inp = torch.unsqueeze(inp, 0)

In [65]:
label_encoder = load_file(label_encoder_path)
num_classes = len(label_encoder.classes_)

In [66]:
# Create model object
model = AttentionModel(vec_len, seq_len, num_classes)

# Load trained weights
model.load_state_dict(torch.load(model_path))

# Move the model to GPU if available
if torch.cuda.is_available():
    model = model.cuda()

# Forward pass
out = torch.squeeze(model(inp))

# Find predicted class
prediction = label_encoder.classes_[torch.argmax(out)]
print(f"Predicted  Class: {prediction}")

Predicted  Class: credit_report
